###
### Run with --env-file .env.staging
###
version: "3.9"
name: petboarding-staging
services:
  api:
    image: "ghcr.io/simsustech/petboarding:staging"
    labels:
      caddy: ${HOSTNAME}
      caddy.reverse_proxy: "{{upstreams 80}}"
    environment:
      # Modular API
      VITE_API_HOSTNAME: ${HOSTNAME}
      OIDC_ISSUER_NAME: ${OIDC_ISSUER_NAME}
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      LICENSE_KEY: ${LICENSE_KEY}
      OTP_SECRET_FILE: /run/secrets/OTP_SECRET
      OTP_VALIDITY_SECONDS: 3600
      EMAIL_FOOTER: "Petboarding"
      VITE_TITLE: Petboarding staging
      VITE_LANG: en-US
      # VITE_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      VITE_ALLOWED_SPECIES: dog
      VITE_DAYCARE_DISABLED_WEEKDAYS: 6,0

    # entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    secrets:
      - POSTGRES_PASSWORD
      - SIMSUSTECH_NPM_TOKEN
      - OTP_SECRET
    networks:
      web:
      petboarding:
        aliases:
          - api
    restart: unless-stopped

  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    networks:
      petboarding:
        aliases:
          - database
    restart: unless-stopped

secrets:
  POSTGRES_PASSWORD:
    file: ./env/POSTGRES_PASSWORD
  SIMSUSTECH_NPM_TOKEN:
    file: ./env/SIMSUSTECH_NPM_TOKEN
  OTP_SECRET:
    file: ./env/OTP_SECRET

networks:
  petboarding:
  web:
    external: true
