version: "3.9"
services:
  api:
    image: "ghcr.io/simsustech/petboarding:latest"
    # volumes:
    # - ./termsandconditions.pdf:/app/node_modules/@petboarding/app/dist/ssr/client/termsandconditions.pdf
    labels:
      caddy: ${HOSTNAME}
      caddy.reverse_proxy: "{{upstreams 80}}"
    environment:
      # Modular API
      VITE_API_HOSTNAME: ${HOSTNAME}
      OIDC_ISSUER_NAME: ${OIDC_ISSUER_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_SECURE: ${MAIL_SECURE}
      LICENSE_KEY: ${LICENSE_KEY}
      OIDC_COOKIES_KEYS: /run/secrets/OIDC_COOKIES_KEYS
      OTP_SECRET_FILE: /run/secrets/OTP_SECRET
      OTP_VALIDITY_SECONDS: 3600
      EMAIL_FOOTER: "Petboarding"
      VITE_TITLE: Petboarding
      VITE_LANG: en-US
      # VITE_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      # Petboarding
      # COUNTRY: US
      VITE_ALLOWED_SPECIES: dog
      VITE_DAYCARE_DISABLED_WEEKDAYS: 6,0
      # VITE_UNIT_OF_MASS: kg # kg | lbs
      # VITE_SLIMFACT_HOSTNAME: xyz.slimfact.app
      # VITE_SLIMFACT_COMPANY_ID: 1
    secrets:
      - POSTGRES_PASSWORD
      - OTP_SECRET
      - OIDC_COOKIES_KEYS
    networks:
      web:
      petboarding:
        aliases:
          - api
    restart: unless-stopped

  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    networks:
      petboarding:
        aliases:
          - database
    restart: unless-stopped

secrets:
  POSTGRES_PASSWORD:
    file: ./env/POSTGRES_PASSWORD
  OTP_SECRET:
    file: ./env/OTP_SECRET
  OIDC_COOKIES_KEYS:
    file: ./env/OIDC_COOKIES_KEYS

networks:
  petboarding:
  web:
    external: true
