packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@vitrify/*"
  - vitrify
  - unocss-preset-quasar
  - "@simsustech/*"
  - "@modular-api/*"
  - unocss
  - "@unocss/*"
  - "@pinia/colada"
  - pg*
  - nodemailer
  - vitrify
  - ajv
