injectWorkspacePackages: true

packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@vitrify/*"
  - vitrify
  - unocss-preset-quasar
  - "@simsustech/*"
  - "@modular-api/*"
  - otplib
  - "@otplib/*"
  - "@vue/*"
  - vue-tsc
  - date-fns

allowBuilds:
  "@parcel/watcher": true
  core-js: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
