packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@vitrify/*"
  - vitrify
  - unocss-preset-quasar
  - "@simsustech/*"
  - "@modular-api/*"
  - unocss
  - "@unocss/*"
  - "@pinia/colada"
  - pg*
  - vite
  - vite
  - oxfmt
  - "@oxfmt/*"
  - oxlint
  - "@oxlint/*"
  - fast-xml-parser
  - playwright
  - playwright-core
  - "@playwright/*"
  - "@types/node"
  - content-type
  - vitest
  - "@vitest/*"
