const dog: Record<string, string[]> = {
  'en-US': [
    'Mixed breed',
    'English Pointer',
    'English Setter',
    'Kerry Blue Terrier',
    'Cairn Terrier',
    'English Cocker Spaniel',
    'Gordon Setter',
    'Airedale Terrier',
    'Australian Terrier',
    'Bedlington Terrier',
    'Border Terrier',
    'Bull Terrier',
    'Fox Terrier (Smooth)',
    'English Toy Terrier (Black&Tan)',
    'Swedish Vallhund',
    'Belgian Shepherd Dog',
    'Old English Sheepdog',
    'Griffon Nivernais',
    'Briquet Griffon Vendeen',
    'Ariegeois',
    'Gascon Saintongeois',
    'Great Gascony Blue',
    'Poitevin',
    'Billy',
    'Artois Hound',
    'Porcelaine',
    'Small Blue Gascony Blue',
    'Blue Gascony Griffon',
    'Grand Basset Griffon Vendeen',
    'Norman Artesien Basset',
    'Blue Gascony Basset',
    'Basset Fauve De Bretagne',
    'Portuguese Water Dog',
    'Welsh Corgi Cardigan',
    'Welsh Corgi Pembroke',
    'Irish Soft Coated Wheaten Terrier',
    'Yugoslavian Shepherd Dog - Sharplanina',
    'Jämthund',
    'Basenji',
    'Berger De Beauce',
    'Bernese Mountain Dog',
    'Appenzell Cattle Dog',
    'Entlebuch Cattle Dog',
    'Karelian Bear Dog',
    'Finnish Spitz',
    'Newfoundland',
    'Finnish Hound',
    'Polish Hound',
    'Komondor',
    'Kuvasz',
    'Puli',
    'Pumi',
    'Hungarian Short-haired Pointer (Vizsla)',
    'Great Swiss Mountain Dog',
    'Swiss Hound',
    'Small Swiss Hound',
    'St. Bernard',
    'Coarse-haired Styrian Hound',
    'Austrian Black and Tan Hound',
    'Austrian  Pinscher',
    'Maltese',
    'Fawn Brittany Griffon',
    'Petit Basset Griffon Vendeen',
    'Tyrolean Hound',
    'Lakeland Terrier',
    'Manchester Terrier',
    'Norwich Terrier',
    'Scottish Terrier',
    'Sealyham Terrier',
    'Skye Terrier',
    'Staffordshire Bull Terrier',
    'Continental Toy Spaniel',
    'Welsh Terrier',
    'Griffon Bruxellois',
    'Griffon Belge',
    'Petit Brabançon',
    'Schipperke',
    'Bloodhound',
    'West Highland White Terrier',
    'Yorkshire Terrier',
    'Catalan Sheepdog',
    'Shetland Sheepdog',
    'Ibizan Podenco',
    'Burgos Pointing Dog',
    'Spanish Mastiff',
    'Pyrenean Mastiff',
    'Portuguese Sheepdog',
    'Portuguese Warren Hound-portuguese Podengo',
    'Brittany Spaniel',
    'Rafeiro of Alentejo',
    'German Spitz',
    'German Wire- Haired Pointing Dog',
    'Weimaraner',
    'Westphalian Dachsbracke',
    'French Bulldog',
    'Kleiner Münsterländer',
    'German Hunting Terrier',
    'German Spaniel',
    'French Water Dog',
    'Blue Picardy Spaniel',
    'Wire-haired Pointing Griffon Korthals',
    'Picardy Spaniel',
    'Clumber Spaniel',
    'Curly Coated Retriever',
    'Golden Retriever',
    'Briard',
    'Pont-audemer Spaniel',
    'Saint Germain Pointer',
    'Dogue De Bordeaux',
    'Deutsch Langhaar',
    'Large Munsterlander',
    'German Short- Haired Pointing Dog',
    'Irish Red Setter',
    'Flat Coated Retriever',
    'Labrador Retriever',
    'Field Spaniel',
    'Irish Water Spaniel',
    'English Springer Spaniel',
    'Welsh Springer Spaniel',
    'Sussex Spaniel',
    'King Charles Spaniel',
    'Smålandsstövare',
    'Drever',
    'Schillerstövare',
    'Hamiltonstövare',
    'French Pointing Dog - Gascogne Type',
    'French Pointing Dog - Pyrenean Type',
    'Swedish Lapphund',
    'Cavalier King Charles Spaniel',
    'Pyrenean Mountain Dog',
    'Pyrenean Sheepdog - Smooth Faced',
    'Irish Terrier',
    'Boston Terrier',
    'Long-haired Pyrenean Sheepdog',
    'Slovakian Chuvach',
    'Dobermann',
    'Boxer',
    'Leonberger',
    'Rhodesian Ridgeback',
    'Rottweiler',
    'Dachshund',
    'Bulldog',
    'Serbian Hound',
    'Istrian Short-haired Hound',
    'Istrian Wire-haired Hound',
    'Dalmatian',
    'Posavatz Hound',
    'Bosnian Broken-haired Hound - Called Barak',
    'Collie Rough',
    'Bullmastiff',
    'Greyhound',
    'English Foxhound',
    'Irish Wolfhound',
    'Beagle',
    'Whippet',
    'Basset Hound',
    'Deerhound',
    'Italian Spinone',
    'German Shepherd Dog',
    'American Cocker Spaniel',
    'Dandie Dinmont Terrier',
    'Fox Terrier (Wire)',
    'Castro Laboreiro Dog',
    'Bouvier Des Ardennes',
    'Poodle',
    'Estrela Mountain Dog',
    'French Spaniel',
    'Picardy Sheepdog',
    'Ariege Pointing Dog',
    'Bourbonnais Pointing Dog',
    'Auvergne Pointer',
    'Giant Schnauzer',
    'Schnauzer',
    'Miniature Schnauzer',
    'German Pinscher',
    'Miniature Pinscher',
    'Affenpinscher',
    'Portuguese Pointing Dog',
    'Sloughi',
    'Finnish Lapphund',
    'Hovawart',
    'Bouvier Des Flandres',
    'Kromfohrländer',
    'Borzoi - Russian Hunting Sighthound',
    'Bergamasco Shepherd Dog',
    'Italian Volpino',
    'Bolognese',
    'Neapolitan Mastiff',
    'Italian Rough-haired Segugio',
    "Cirneco Dell'etna",
    'Italian Greyhound',
    'Maremma and the Abruzzes Sheepdog',
    'Italian Pointing Dog',
    'Norwegian Hound',
    'Spanish Hound',
    'Chow Chow',
    'Japanese Chin',
    'Pekingese',
    'Shih Tzu',
    'Tibetan Terrier',
    'Samoyed',
    'Hanoverian Scenthound',
    'Hellenic Hound',
    'Bichon Frise',
    'Pudelpointer',
    'Bavarian Mountain Scent Hound',
    'Chihuahua',
    'French Tricolour Hound',
    'French White & Black Hound',
    'Frisian Water Dog',
    'Stabijhoun',
    'Dutch Shepherd Dog',
    'Drentsche Partridge Dog',
    'Fila Brasileiro',
    'Landseer (European Continental Type)',
    'Lhasa Apso',
    'Afghan Hound',
    'Serbian Tricolour Hound',
    'Tibetan Mastiff',
    'Tibetan Spaniel',
    'Deutsch Stichelhaar',
    'Little Lion Dog',
    'Xoloitzcuintle',
    'Great Dane',
    'Australian Silky Terrier',
    'Norwegian Buhund',
    'Mudi',
    'Hungarian Wire-haired Pointer',
    'Hungarian Greyhound',
    'Hungarian Hound - Transylvanian Scent Hound',
    'Norwegian Elkhound Grey',
    'Alaskan Malamute',
    'Slovakian Hound',
    'Bohemian Wire-haired Pointing Griffon',
    'Cesky Terrier',
    'Atlas Mountain Dog (Aidi)',
    'Pharaoh Hound',
    'Majorca Mastiff',
    'Havanese',
    'Polish Lowland Sheepdog',
    'Tatra Shepherd Dog',
    'Pug',
    'Alpine Dachsbracke',
    'Akita',
    'Shiba',
    'Japanese Terrier',
    'Tosa',
    'Hokkaido',
    'Japanese Spitz',
    'Chesapeake Bay Retriever',
    'Mastiff',
    'Norwegian Lundehund',
    'Hygen Hound',
    'Halden Hound',
    'Norwegian Elkhound Black',
    'Saluki',
    'Siberian Husky',
    'Bearded Collie',
    'Norfolk Terrier',
    'Canaan Dog',
    'Greenland Dog',
    'Norrbottenspitz',
    'Croatian Shepherd Dog',
    'Karst Shepherd Dog',
    'Montenegrin Mountain Hound',
    'Old Danish Pointing Dog',
    'Grand Griffon Vendeen',
    'Coton De Tulear',
    'Lapponian Herder',
    'Spanish Greyhound',
    'American Staffordshire Terrier',
    'Australian Cattle Dog',
    'Chinese Crested Dog',
    'Icelandic Sheepdog',
    'Beagle Harrier',
    'Eurasian',
    'Dogo Argentino',
    'Australian Kelpie',
    'Otterhound',
    'Harrier',
    'Collie Smooth',
    'Border Collie',
    'Romagna Water Dog',
    'German Hound',
    'Black and Tan Coonhound',
    'American Water Spaniel',
    'Irish Glen of Imaal Terrier',
    'American Foxhound',
    'Russian-european Laika',
    'East Siberian Laika',
    'West Siberian Laika',
    'Azawakh',
    'Dutch Smoushond',
    'Shar Pei',
    'Peruvian Hairless Dog',
    'Saarloos Wolfhond',
    'Nova Scotia Duck Tolling Retriever',
    'Dutch Schapendoes',
    'Nederlandse Kooikerhondje',
    'Broholmer',
    'French White and Orange Hound',
    'Kai',
    'Kishu',
    'Shikoku',
    'Wirehaired Slovakian Pointer',
    'Majorca Shepherd Dog',
    'Great Anglo-french Tricolour Hound',
    'Great Anglo-french White and Black Hound',
    'Great Anglo-french White ',
    'Medium-sized Anglo-french Hound',
    'South Russian Shepherd Dog',
    'Russian Black Terrier',
    'Caucasian Shepherd Dog',
    'Canarian Warren Hound',
    'Irish Red and White Setter',
    'Anatolian Shepherd Dog',
    'Czechoslovakian Wolfdog',
    'Polish Greyhound',
    'Korea Jindo Dog',
    'Central Asia Shepherd Dog',
    'Spanish Water Dog',
    'Italian Short-haired Segugio',
    'Thai Ridgeback Dog',
    'Parson Russell Terrier',
    'Saint Miguel Cattle Dog',
    'Brazilian Terrier',
    'Australian Shepherd',
    'Italian Corso Dog',
    'American Akita',
    'Jack Russell Terrier',
    'Dogo Canario',
    'White Swiss Shepherd Dog',
    'Taiwan Dog',
    'Romanian Mioritic Shepherd Dog',
    'Romanian Carpathian Shepherd Dog',
    'Australian Stumpy Tail Cattle Dog',
    'Russian Toy',
    'Cimarrón Uruguayo',
    'Polish Hunting Dog',
    'Bosnian and Herzegovinian - Croatian Shepherd Dog',
    'Danish-swedish Farmdog',
    'Southeastern European Shepherd',
    'Thai Bangkaew Dog',
    'Miniature Bull Terrier',
    'Lancashire Heeler'
  ],
  nl: [
    'Kruising',
    'Pointer',
    'Engelse setter',
    'Kerry blue-terriër',
    'Cairnterriër',
    'Engelse cockerspaniël',
    'Gordon setter',
    'Airedaleterriër',
    'Australische terriër',
    'Bedlingtonterriër',
    'Borderterriër',
    'Bulterriër',
    'Foxterriër - gladhaar',
    'Engelse toyterriër',
    'Västgötaspets',
    'Belgische herder',
    'Old English Sheepdog (bobtail)',
    'Griffon nivernais',
    'Briquet griffon vendéen',
    'Ariégeois',
    'Grand Gascon saintongeois',
    'Grand bleu de Gascogne',
    'Poitevin',
    'Billy',
    "Chien d'Artois",
    'Porcelaine',
    'Petit bleu de Gascogne',
    'Griffon bleu de Gascogne',
    'Grand basset griffon vendéen',
    'Basset artésien normand',
    'Basset bleu de Gascogne',
    'Basset fauve de Bretagne',
    'Portugese waterhond',
    'Welsh corgi Cardigan',
    'Welsh corgi Pembroke',
    'Irish soft-coated wheaten terrier',
    'Šarplaninac',
    'Jämthund',
    'Basenji',
    'Beauceron',
    'Berner sennenhond',
    'Appenzeller sennenhond',
    'Entlebucher sennenhond',
    'Karelische berenhond',
    'Finse spits',
    'Newfoundlander',
    'Finse brak',
    'Ogar polski',
    'Komondor',
    'Kuvasz',
    'Puli',
    'Pumi',
    'Vizsla - korthaar',
    'Grote Zwitserse sennenhond',
    'Schweizer Laufhund',
    'Schweizerischer Niederlaufhund',
    'Sint-bernard',
    'Steirische rauhhaarbracke',
    'Brandlbracke',
    'Oostenrijkse pinscher',
    'Maltezer',
    'Griffon fauve de Bretagne',
    'Petit basset griffon vendéen',
    'Tiroler brak',
    'Lakelandterriër',
    'Manchesterterriër',
    'Norwichterriër',
    'Schotse terriër',
    'Sealyhamterriër',
    'Skyeterriër',
    'Staffordshire-bulterriër',
    'Épagneul nain continental',
    'Welsh terriër',
    'Griffon bruxellois',
    'Griffon belge',
    'Petit brabançon',
    'Schipperke',
    'Bloedhond',
    'West Highland white terrier',
    'Yorkshireterriër',
    'Catalaanse herder',
    'Sheltie',
    'Podenco ibicenco',
    'Perdigueiro de Burgos',
    'Mastín español',
    'Mastín del Pirineo',
    'Cão da Serra de Aires',
    'Podengo português',
    'Epagneul breton',
    'Rafeiro do Alentejo',
    'Keeshond',
    'Duitse staande hond (draadhaar)',
    'Weimarse staande hond',
    'Westfaalse dasbrak',
    'Franse buldog',
    'Kleine Münsterländer',
    'Duitse jachtterriër',
    'Duitse wachtelhond',
    'Barbet',
    'Epagneul bleu de Picardie',
    'Griffon Korthals',
    'Epagneul picard',
    'Clumberspaniël',
    'Curly coated retriever',
    'Golden retriever',
    'Briard',
    'Epagneul de Pont-Audemer',
    'Braque Saint-Germain',
    'Bordeauxdog',
    'Duitse staande hond (langhaar)',
    'Grote Münsterländer',
    'Duitse staande hond (korthaar)',
    'Ierse setter',
    'Flatcoated retriever',
    'Labrador retriever',
    'Fieldspaniël',
    'Ierse waterspaniël',
    'Engelse springerspaniël',
    'Welshe springerspaniël',
    'Sussex-spaniël',
    'King Charles-spaniël',
    'Smalandstövare',
    'Drever',
    'Schillerstövare',
    'Hamiltonstövare',
    'Braque français, type Gascogne',
    'Braque français, type Pyrénées',
    'Zweedse lappenhond',
    'Cavalier King Charles-spaniël',
    'Pyrenese berghond',
    'Pyrenese herdershond à Face Rase',
    'Ierse terriër',
    'Bostonterriër',
    'Pyrenese herdershond à Poil Long',
    'Slovenský čuvač',
    'Dobermann',
    'Boxer',
    'Leonberger',
    'Pronkrug',
    'Rottweiler',
    'Teckel',
    'Engelse buldog',
    'Srpski gonic',
    'Istarski kratkodlaki gonic',
    'Istarski ostrodlaki gonic',
    'Dalmatiër',
    'Posavski gonic',
    'Bosanski ostrodlaki gonic barak',
    'Schotse herdershond - langhaar',
    'Bullmastiff',
    'Greyhound',
    'Foxhound',
    'Ierse wolfshond',
    'Beagle',
    'Whippet',
    'Basset hound',
    'Deerhound',
    'Spinone italiano',
    'Duitse herder',
    'Amerikaanse cockerspaniël',
    'Dandie Dinmont-terriër',
    'Foxterriër - draadhaar',
    'Cão de Castro Laboreiro',
    'Bouvier des Ardennes',
    'Franse poedel',
    'Cão da Serra da Estrela',
    'Epagneul français',
    'Picardische herdershond',
    "Braque de l'Ariège",
    'Braque du Bourbonnais',
    "Braque d'Auvergne",
    'Riesenschnauzer',
    'Middenslagschnauzer',
    'Dwergschnauzer',
    'Duitse pinscher',
    'Dwergpinscher',
    'Affenpinscher',
    'Perdigueiro português',
    'Sloughi',
    'Finse lappenhond',
    'Hovawart',
    'Vlaamse koehond',
    'Kromfohrländer',
    'Barzoi',
    'Bergamasco',
    'Volpino italiano',
    'Bolognezer',
    'Mastino napoletano',
    'Segugio italiano - ruwhaar',
    "Cirneco dell'Etna",
    'Italiaans windhondje',
    'Berghond van de Maremmen en Abruzzen',
    'Bracco italiano',
    'Dunker',
    'Sabueso español',
    'Chowchow',
    'Japanse spaniël',
    'Pekingees',
    'Shih tzu',
    'Tibetaanse terriër',
    'Samojeed',
    'Hannoveraanse zweethond',
    'Hellinikos ichnilatis',
    'Bichon frisé',
    'Poedelpointer',
    'Beierse bergzweethond',
    'Chihuahua',
    'Français tricolore',
    'Français blanc et noir',
    'Wetterhoun',
    'Stabij',
    'Hollandse herder',
    'Drentsche patrijshond',
    'Fila brasileiro',
    'Landseer ECT',
    'Lhasa apso',
    'Afghaanse windhond',
    'Srpski trobojni gonic',
    'Tibetaanse mastiff',
    'Tibetaanse spaniël',
    'Duitse staande hond (stekelhaar)',
    'Leeuwhondje',
    'Mexicaanse naakthond',
    'Duitse dog',
    'Australische silkyterriër',
    'Noorse buhund',
    'Mudi',
    'Vizsla - draadhaar',
    'Hongaarse windhond',
    'Erdélyi kopó',
    'Noorse elandhond - grijs',
    'Alaska-malamute',
    'Slovensky kopov',
    'Český fousek',
    'Ceskyterriër',
    'Aidi',
    'Pharaohond',
    'Ca de Bou',
    'Havanezer',
    'Polski owczarek nizinny',
    'Tatrahond',
    'Mopshond',
    'Alpenländische Dachsbracke',
    'Akita',
    'Shiba',
    'Japanse terriër',
    'Tosa',
    'Hokkaido',
    'Japanse spits',
    'Chesapeake Bayretriever',
    'Mastiff',
    'Noorse lundehond',
    'Hygenhund',
    'Haldenstøvare',
    'Noorse elandhond - zwart',
    'Saluki',
    'Siberische husky',
    'Bearded collie',
    'Norfolkterriër',
    'Kanaänhond',
    'Groenlandse hond',
    'Norrbottenspets',
    'Kroatische herder',
    'Kraški ovčar',
    'Crnogorski planinski gonic',
    'Gammel dansk hønsehund',
    'Grand griffon vendéen',
    'Coton de Tuléar',
    'Lapinporokoira',
    'Galgo español',
    'Amerikaanse staffordshireterriër',
    'Australische veedrijvershond',
    'Chinese gekuifde naakthond',
    'IJslandse hond',
    'Beagle-harrier',
    'Eurasiër',
    'Argentijnse dog',
    'Kelpie',
    'Otterhound',
    'Harrier',
    'Schotse herdershond - korthaar',
    'Bordercollie',
    'Lagotto romagnolo',
    'Duitse brak',
    'Black and tan coonhound',
    'Amerikaanse waterspaniël',
    'Glen of Imaalterriër',
    'American foxhound',
    'Russisch-Europese laika',
    'Oost-Siberische laika',
    'Westsiberische laika',
    'Azawakh',
    'Hollandse smoushond',
    'Shar-pei',
    'Peruaanse naakthond',
    'Saarlooswolfhond',
    'Nova Scotia duck tolling retriever',
    'Schapendoes',
    'Kooikerhondje',
    'Broholmer',
    'Français blanc et orange',
    'Kai',
    'Kishu',
    'Shikoku',
    'Slovenský hrubosrstý stavač',
    'Ca de bestiar',
    'Grand anglo-français tricolore',
    'Grand anglo-français blanc et noir',
    'Grand anglo-français blanc et orange',
    'Anglo-français de petit vénerie',
    'Zuid-Russische owcharka',
    'Zwarte Russische terriër',
    'Kaukasische owcharka',
    'Podenco canario',
    'Rood-witte Ierse setter',
    'Anatolische herder',
    'Tsjecho-Slowaakse wolfhond',
    'Chart polski',
    'Koreaanse jindohond',
    'Centraal-Aziatische owcharka',
    'Perro de agua español',
    'Segugio italiano - korthaar',
    'Thai ridgebackdog',
    'Parson Russell-terriër',
    'Cão de fila de São Miguel',
    'Braziliaanse terriër',
    'Australische herder',
    'Cane corso',
    'Amerikaanse akita',
    'Jack Russell Terriër',
    'Dogo canario',
    'Zwitserse witte herder',
    'Taiwandog',
    'Ciobanesc romanesc mioritic',
    'Ciobanesc romanesc carpatin',
    'Australian stumpy tail cattle dog',
    'Russische toyterriër',
    'Cimarrón Uruguayo',
    'Gończy Polski',
    'Tornjak',
    'Deens-Zweedse boerderijhond',
    'Ciobanesc Romanesc de Bucovina',
    'Thai Bangkaew Dog',
    'Miniatuur Bull Terrier',
    'Lancashire Heeler'
  ]
}

const cat: Record<string, string[]> = {
  'en-US': [],
  nl: []
}

export default {
  dog,
  cat
}
